import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Zafack Billy
 */
public class Stock extends javax.swing.JDialog {

	class Actions implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			if (e.getSource() == pAnnuler) {
				setVisible(false);
			}
			if (e.getSource() == pReprendre) {
				pNom.setText("");
				pID.setText("");
				spinner.setValue(0);
				pAchat.setText("");
				pVente.setText("");
			}
			if (e.getSource() == pConfirmer) {
				insertionProduit();
				insertionStock();
				JOptionPane.showMessageDialog(null,
						"Ce produit a ete enregistré", "PRODUIT ENREGISTREE",
						JOptionPane.INFORMATION_MESSAGE);
				setVisible(false);
			}
		}

	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;

	private javax.swing.JLabel jLabel4;

	private javax.swing.JLabel jLabel5;

	private javax.swing.JLabel jLabel6;

	private javax.swing.JLabel jLabel7;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JTextField pAchat;
	private javax.swing.JButton pAnnuler;
	private javax.swing.JButton pConfirmer;
	private javax.swing.JTextField pID;
	private javax.swing.JTextField pNom;
	private javax.swing.JButton pReprendre;
	private javax.swing.JTextField pUnite;
	private javax.swing.JTextField pVente;
	private javax.swing.JSpinner spinner;

	// End of variables declaration
	/**
	 * Creates new form Stock
	 */
	public Stock(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		pConfirmer.addActionListener(new Actions());
		pAnnuler.addActionListener(new Actions());
		pReprendre.addActionListener(new Actions());
		pID.setEnabled(false);
		String d = getLPIDD();
		System.out.println("WW " + d);
		d = d.substring(1, d.length());
		System.out.println("WW " + d);
		int i = Integer.parseInt(d);
		System.out.println("WW " + i);
		i++;
		System.out.println("WW " + i);
		pID.setText("P" + Integer.toString(i));

	}

	public String getLPIDD() {
		String ss = "";
		try {
			Statement stmt = Fenetre.getConnection().createStatement();
			ResultSet r = stmt
					.executeQuery("SELECT Identification_P FROM Produit");

			if (r.last()) {
				ss = r.getString("Identification_P");
			} else {
				ss = "P0";
			}
		} catch (SQLException s) {
			s.printStackTrace();
		}
		return ss;
	}

	public String getPID(String s) {
		String ss = "";
		try {
			Statement stmt = Fenetre.getConnection().createStatement();
			ResultSet r = stmt
					.executeQuery("SELECT ProduitID FROM Produit WHERE Identification_P="
							+ s);

			if (r.next()) {
				ss = r.getString("ProduitID");
			}
		} catch (SQLException s1) {
			s1.printStackTrace();
		}
		return ss;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		pConfirmer = new javax.swing.JButton();
		pAnnuler = new javax.swing.JButton();
		pReprendre = new javax.swing.JButton();
		pID = new javax.swing.JTextField();
		pNom = new javax.swing.JTextField();
		pAchat = new javax.swing.JTextField();
		pVente = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		pUnite = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		spinner = new javax.swing.JSpinner();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
		jLabel1.setText("NOUVEAU PRODUIT EN STOCK");

		jLabel2.setText("IDENTIFICATION : *");

		jLabel3.setText("NOM DU PRODUIT : *");

		jLabel4.setText("PRIX D'ACHAT UNITAIRE :");

		jLabel5.setText("PRIX DE VENTE UNITAIRE:");

		pConfirmer.setText("Confirmer");

		pAnnuler.setText("Annuler");

		pReprendre.setText("Reprendre");

		pVente.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pVenteActionPerformed(evt);
			}
		});

		jLabel6.setText("UNITE : *");

		jLabel7.setText("NOMBRE D'UNITES :");

		spinner.setModel(new javax.swing.SpinnerNumberModel());

		JLabel lblFcfa = new JLabel("FCFA");

		JLabel label = new JLabel("FCFA");

		javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(
				jPanel1);
		gl_jPanel1
				.setHorizontalGroup(gl_jPanel1
						.createParallelGroup(Alignment.TRAILING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGap(84)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addComponent(
																				pVente,
																				253,
																				253,
																				253))
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addComponent(
																				pAchat,
																				254,
																				254,
																				254))
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addGroup(
																				gl_jPanel1
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addGroup(
																								gl_jPanel1
																										.createSequentialGroup()
																										.addGap(1)
																										.addComponent(
																												jLabel2))
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								pReprendre))
																		.addGap(42)
																		.addGroup(
																				gl_jPanel1
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								pNom,
																								245,
																								245,
																								245)
																						.addComponent(
																								pID,
																								245,
																								245,
																								245)
																						.addComponent(
																								pUnite,
																								245,
																								245,
																								245)
																						.addComponent(
																								spinner,
																								GroupLayout.PREFERRED_SIZE,
																								109,
																								GroupLayout.PREFERRED_SIZE))))
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addGap(32)
																		.addComponent(
																				pAnnuler))
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addGroup(
																				gl_jPanel1
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								label,
																								GroupLayout.PREFERRED_SIZE,
																								26,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblFcfa))))
										.addGap(45))
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGap(0, 291, Short.MAX_VALUE)
										.addComponent(pConfirmer,
												GroupLayout.PREFERRED_SIZE, 90,
												GroupLayout.PREFERRED_SIZE)
										.addGap(240))
						.addGroup(
								gl_jPanel1.createSequentialGroup().addGap(144)
										.addComponent(jLabel1)
										.addContainerGap(193, Short.MAX_VALUE)));
		gl_jPanel1
				.setVerticalGroup(gl_jPanel1
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGap(35)
										.addComponent(jLabel1)
										.addGap(18)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																pID,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(38)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																pNom,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(35)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																pUnite,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(45)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																spinner,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.RELATED, 52,
												Short.MAX_VALUE)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																pAchat,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(lblFcfa))
										.addGap(40)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																pVente,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(
																label,
																GroupLayout.PREFERRED_SIZE,
																14,
																GroupLayout.PREFERRED_SIZE))
										.addGap(49)
										.addComponent(pConfirmer,
												GroupLayout.PREFERRED_SIZE, 32,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																pReprendre)
														.addComponent(pAnnuler))
										.addGap(27)));
		jPanel1.setLayout(gl_jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 621, Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 545, Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>

	public void insertionProduit() {

		try {
			Statement stmt = Fenetre.getConnection().createStatement();
			ResultSet set = SelectBDP(pID.getText());
			if (set.next()) {
				JOptionPane
						.showMessageDialog(
								this,
								"Un Produit ayant cet identificateur existe deja. Veuillez le changer !",
								"DUPLICATION D'IDENTIFICATION", 1);
			} else {
				int a = stmt
						.executeUpdate("INSERT INTO Produit(Identification_P,Nom,Unite,PrixAchat,PrixVente)  VALUES (\""
								+ pID.getText()
								+ "\",\""
								+ pNom.getText()
								+ "\",\""
								+ pUnite.getText()
								+ "\",\""
								+ pAchat.getText()
								+ "\",\""
								+ pVente.getText()
								+ "\");");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		revalidate();
	}

	public void insertionStock() {

		try {
			Statement stmt = Fenetre.getConnection().createStatement();

			int a = stmt
					.executeUpdate("INSERT INTO Stock(Nom,Unite,NbUnite,PrixAchat,PrixVente)  VALUES (\""
							+ pNom.getText()
							+ "\",\""
							+ pUnite.getText()
							+ "\",\""
							+ spinner.getValue()
							+ "\",\""
							+ pAchat.getText()
							+ "\",\""
							+ pVente.getText()
							+ "\");");

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		revalidate();
	}

	private void pVenteActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * Permet d'obtenir les informations sur un etudiant de la table Etudiant
	 * 
	 * @param mat
	 *            Le matricule de l'etudiant en question
	 * @return ResultSet des informations
	 */
	public ResultSet SelectBDP(String id) {
		ResultSet resultats = null;

		try {
			PreparedStatement stmt = Fenetre.getConnection().prepareStatement(
					"SELECT * FROM Produit WHERE Identification_P=?");
			stmt.setString(1, id);
			resultats = stmt.executeQuery();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return resultats;
	}

	/**
	 * Permet d'obtenir les informations sur un etudiant de la table Etudiant
	 * 
	 * @param mat
	 *            Le matricule de l'etudiant en question
	 * @return ResultSet des informations
	 */
	public ResultSet SelectBDS(String id) {
		ResultSet resultats = null;

		try {
			PreparedStatement stmt = Fenetre.getConnection().prepareStatement(
					"SELECT * FROM Stock WHERE ProduitID=?");
			stmt.setString(1, id);
			resultats = stmt.executeQuery();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return resultats;
	}
}
