import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.ListModel;

public class CreerDept extends JDialog {

	class Action implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			if (e.getSource() == annuler) {
				setVisible(false);
			}
			if (e.getSource() == confirmer) {
				ListModel<String> l = Init.getDepartementActuel().getModel();
				DefaultListModel<String> l1 = new DefaultListModel<String>();
				for (int i = 0; i < l.getSize(); i++) {
					l1.addElement(l.getElementAt(i));
				}
				l1.addElement(nomDept.getText());
				Init.getDepartementActuel().setModel(l1);
				if (!Interface_TP2.getDepartements()
						.contains(nomDept.getText())) {
					Interface_TP2.getDepartements().add(nomDept.getText());
				}
				Init.getNbDepartement().setText(
						Integer.toString(Integer.parseInt(Init
								.getNbDepartement().getText()) + 1));
				setVisible(false);
			}
		}

	}

	// Variables declaration - do not modify
	private javax.swing.JButton annuler;

	private javax.swing.JButton confirmer;

	private javax.swing.JLabel label_1;
	private javax.swing.JLabel lblNouveauEtudiant;
	private javax.swing.JTextField nomDept;

	// End of variables declaration
	public CreerDept(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lblNouveauEtudiant = new javax.swing.JLabel();
		confirmer = new javax.swing.JButton();
		annuler = new javax.swing.JButton();
		label_1 = new javax.swing.JLabel();
		nomDept = new javax.swing.JTextField();

		annuler.addActionListener(new Action());
		confirmer.addActionListener(new Action());
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblNouveauEtudiant.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
		lblNouveauEtudiant.setText("NOUVEAU  ETUDIANT");

		confirmer.setText("Confirmer");

		annuler.setText("Annuler");

		label_1.setText("NOM :");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(172,
																						172,
																						172)
																				.addComponent(
																						lblNouveauEtudiant))
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(139,
																						139,
																						139)
																				.addComponent(
																						label_1)
																				.addGap(18,
																						18,
																						18)
																				.addComponent(
																						nomDept,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						231,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		confirmer)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		annuler)
																.addGap(17, 17,
																		17)))
								.addContainerGap(126, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(62, 62, 62)
								.addComponent(lblNouveauEtudiant)
								.addGap(89, 89, 89)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(label_1)
												.addComponent(
														nomDept,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(104, 104, 104)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(confirmer)
												.addComponent(annuler))
								.addContainerGap(38, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
}
